function out1 = rbfgrad_file(x,y,z)
%RBFGRAD_FILE
%    OUT1 = RBFGRAD_FILE(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Nov-2022 11:31:17

t2 = x.^2;
t3 = y.^2;
t4 = z.^2;
t5 = t2+t3+t4+1.0e-5;
t6 = sqrt(t5);
t7 = 1.0./t6;
t8 = t6-1.0;
out1 = [t7.*t8.*x.*2.0;t7.*t8.*y.*2.0;t7.*t8.*z.*2.0];
