function out1 = rbfhessian_file(x,y,z)
%RBFHESSIAN_FILE
%    OUT1 = RBFHESSIAN_FILE(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Nov-2022 10:45:43

t2 = x.^2;
t3 = y.^2;
t4 = z.^2;
t5 = t2+t3+t4+1.0e-5;
t6 = 1.0./t5;
t7 = sqrt(t5);
t8 = 1.0./t7;
t10 = t6.*x.*y.*2.0;
t11 = t6.*x.*z.*2.0;
t12 = t6.*y.*z.*2.0;
t13 = t7-1.0;
t9 = t8.^3;
t14 = t8.*t13.*2.0;
t15 = t9.*t13.*x.*y.*2.0;
t16 = t9.*t13.*x.*z.*2.0;
t17 = t9.*t13.*y.*z.*2.0;
t18 = -t15;
t19 = -t16;
t20 = -t17;
t21 = t10+t18;
t22 = t11+t19;
t23 = t12+t20;
out1 = reshape([t14+t2.*t6.*2.0-t2.*t9.*t13.*2.0,t21,t22,t21,t14+t3.*t6.*2.0-t3.*t9.*t13.*2.0,t23,t22,t23,t14+t4.*t6.*2.0-t4.*t9.*t13.*2.0],[3,3]);
